---
- name: Pull Docker image of DevOpsCalc
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull image calcdevops image
      docker_image:
        name: brahma99/calcdevops
        source: pull